### ISSUE TITLE
Bug: 莫名奇妙的重复涟漪动画

### ISSUE THREAD

**Issue by Subilan** [sotapmc/Monologue#6]
如图，当反选时会出现重复的涟漪动画，引起不适

![show](https://user-images.githubusercontent.com/36447840/81585382-aba99400-93e6-11ea-83fe-4aa09c2ec302.gif)

这个自动 disable 超出数量的项目的功能实现在 `@/views/VoteViewer.vue` 内，核心代码位于 `:76` 到 `:87`。

![image](https://user-images.githubusercontent.com/36447840/81585522-de538c80-93e6-11ea-976b-278b39697578.png)

目前推测应该是第 84 行所导致的，可能需要集中测试调查。

```js
this.multipleDisabled = fillArray(this.multipleDisabled, false, this.items.length, true);
```

**Comment by WindSpiritSR** [comment]
尝试通过很简单的方法操作checkbox后问题依然存在，可能是material的锅

**Comment by Subilan** [comment]
case closed due to unfixability
